"""PDF extraction and the page map.

The PDFs here are generated by tests/pdf_fixtures.py, so they are real files with a real
text layer and no binary blobs in the repository.
"""

from pathlib import Path

import pytest
from pdf_fixtures import make_pdf

from voicelm.domain.models import PageSpan
from voicelm.ingestion.pdf import (
    CorruptPdf,
    NoTextLayer,
    assemble_pages,
    extract_pages,
)


def write_pdf(folder: Path, name: str, pages: list[str]) -> Path:
    path = folder / name
    path.write_bytes(make_pdf(pages))
    return path


# --- extraction ------------------------------------------------------------------------


def test_extracts_one_string_per_page_in_order(tmp_path: Path) -> None:
    path = write_pdf(tmp_path, "bio.pdf", ["Mitochondria make ATP.", "Ribosomes build."])

    pages = extract_pages(path)

    assert len(pages) == 2
    assert "Mitochondria" in pages[0]
    assert "Ribosomes" in pages[1]


def test_line_breaks_within_a_page_survive(tmp_path: Path) -> None:
    path = write_pdf(tmp_path, "two_lines.pdf", ["First line.\nSecond line."])

    assert extract_pages(path)[0].splitlines() == ["First line.", "Second line."]


def test_empty_pages_are_kept_so_later_pages_keep_their_numbers(tmp_path: Path) -> None:
    path = write_pdf(tmp_path, "gap.pdf", ["Page one.", "", "Page three."])

    pages = extract_pages(path)

    assert len(pages) == 3
    assert pages[1].strip() == ""


def test_a_pdf_with_no_text_anywhere_is_refused(tmp_path: Path) -> None:
    """What a scan looks like: pages exist, none of them carry text."""
    path = write_pdf(tmp_path, "scan.pdf", ["", ""])

    with pytest.raises(NoTextLayer, match="OCR"):
        extract_pages(path)


def test_a_file_that_is_not_a_pdf_is_refused(tmp_path: Path) -> None:
    path = tmp_path / "lying.pdf"
    path.write_bytes(b"this is not a PDF at all")

    with pytest.raises(CorruptPdf):
        extract_pages(path)


def test_a_missing_file_raises_file_not_found(tmp_path: Path) -> None:
    with pytest.raises(FileNotFoundError):
        extract_pages(tmp_path / "absent.pdf")


# --- the page map ----------------------------------------------------------------------


def test_spans_index_into_the_assembled_text() -> None:
    """The invariant the whole design rests on: a span really points at that page."""
    text, spans = assemble_pages(["Page one.", "Page two.", "Page three."])

    assert len(spans) == 3
    for span, expected in zip(spans, ["Page one.", "Page two.", "Page three."], strict=True):
        assert text[span.start_char : span.end_char] == expected


def test_pages_are_joined_by_one_blank_line() -> None:
    text, _ = assemble_pages(["First.", "Second."])

    assert text == "First.\n\nSecond."


def test_spans_are_numbered_from_one() -> None:
    _, spans = assemble_pages(["a", "b"])

    assert [span.number for span in spans] == [1, 2]


def test_a_blank_page_gets_no_span_but_does_not_renumber_the_rest() -> None:
    text, spans = assemble_pages(["Real page.", "   \n  ", "Also real."])

    assert [span.number for span in spans] == [1, 3]
    assert text == "Real page.\n\nAlso real."
    assert text[spans[1].start_char : spans[1].end_char] == "Also real."


def test_pages_are_cleaned_individually() -> None:
    text, spans = assemble_pages(["  Trailing spaces here   \n\n\n\nand a big gap.  "])

    assert text == "Trailing spaces here\n\nand a big gap."
    assert text[spans[0].start_char : spans[0].end_char] == text


def test_assembled_text_needs_no_second_cleaning_pass() -> None:
    """If a second pass changed the text, every recorded offset would be wrong."""
    from voicelm.ingestion.cleaning import clean_text

    text, _ = assemble_pages(["One.  \n\n\n\nTwo.", "", "  Three.  "])

    assert clean_text(text) == text


def test_a_document_with_no_usable_pages_assembles_to_nothing() -> None:
    assert assemble_pages(["", "  "]) == ("", ())


def test_spans_never_overlap_and_stay_in_order() -> None:
    _, spans = assemble_pages([f"Page number {index}." for index in range(1, 6)])

    for earlier, later in zip(spans, spans[1:], strict=False):
        assert earlier.end_char < later.start_char


def test_page_span_is_immutable() -> None:
    span = PageSpan(number=1, start_char=0, end_char=5)

    with pytest.raises(AttributeError):
        span.number = 2  # type: ignore[misc]


def test_pdf_ligatures_become_the_letters_a_searcher_would_type() -> None:
    text, _ = assemble_pages(["Cataract identi\ufb01cation."])

    assert "identification" in text
    assert "\ufb01" not in text
